# Generated by Django 4.1.2 on 2022-10-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('hubdeviceid', models.CharField(max_length=20)),
            ],
        ),
    ]
